version: "2.4"

services:
  accounts:
    image: eazybyte/accounts:latest
    ports:
      - "8080:8080"
    environment:
      - HELLO=WORLD
    mem_limit: 400m
    networks:
      - eazybank-network
  loans:
    image: eazybyte/loans:latest
    ports:
      - "8090:8090"
    environment:
      - BPL_JVM_THREAD_COUNT=20
    mem_limit: 400m
    networks:
      - eazybank-network
  cards:
    image: eazybyte/cards:latest
    ports:
      - "9000:9000"
    environment:
      - BPL_JVM_THREAD_COUNT=15
    mem_limit: 400m
    networks:
      - eazybank-network

networks:
  eazybank-network: