### See https://www.jetbrains.com/help/idea/exploring-http-syntax.html#enable-disable-saving-request
// @no-log
POST http://localhost:8080/myAccount
Content-Type: application/json

{
  "customerId": 1
}

### Get account config(via config server)
GET http://localhost:8080/accounts/config

### Refresh accounts properties
// @no-log
POST http://localhost:8080/actuator/refresh

### Get listing of activeProfiles and propertySources(keyed by following listed names)
### - server.ports
### - servletContextInitParams
### - systemProperties
### - systemEnvironment
### - springCloudClientHostInfo
### - configserver:https://github.com/joma74/microservices-with-spring/configserver/src/main/resources/config/accounts.properties"
### - configClient
### - Config resource 'class path resource [application.properties]' via location 'optional:classpath:/'
GET http://localhost:8080/actuator/env

###
GET http://localhost:8080/actuator/info
Accept: application/vnd.spring-boot.actuator.v3+json

### shutdown accounts
POST http://localhost:8080/actuator/shutdown

### Gte Accounts deatils with cards and loans via feign client
POST http://localhost:8080/myCustomerDetails
Content-Type: application/json

{
  "customerId": 1
}