### See https://www.jetbrains.com/help/idea/exploring-http-syntax.html#enable-disable-saving-request
// @no-log
POST http://localhost:9000/myCards
Content-Type: application/json

{
  "customerId": 1
}

###
GET http://localhost:9000/cards/config

###
// @no-log
POST http://localhost:9000/actuator/refresh