### See https://www.jetbrains.com/help/idea/exploring-http-syntax.html#enable-disable-saving-request
// @no-log
POST http://localhost:8090/myLoans
Content-Type: application/json

{
  "customerId": 1
}